spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/Tp2-back
        username: postgres
        password: 
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

chatgpt:
  api-key: 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